[package]
name = "ruizukun-dev/matter"
description = "A modern reactive UI library, built specifically for Roblox and Luau"
license = "MIT"
authors = ["freddylist"]
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["*"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
Llama = "ruizukun-dev/llama@1.0.0"